---

- name: test awx playbook
  hosts: all
  gather_facts: True
  tasks:
    - name: test connectivity
      setup:
    - name: print os family of the host
      debug:
        var:  ansible_os_family
    - name: print os family
      debug:
        msg: "ansible awx job-template work fine"
    - name: Create file hello-world 
      blockinfile: 
        path: /root/hello-world.txt
        block: |
        ceci est un text genere avec
        awx platform

        made by patrick
        insertbefore: "BOF"
        create: yes
        
