---

- name: test awx playbook
  hosts: all
  gather_facts: True
  tasks:
    - name: test connectivity
      setup:
    - name: print os family
      debug:
        var:  ansible_os_family
    
    - name: print os family
          debug:
            msg:  "awx job template work fine"
